service: ipe # Name whatever as you like!
plugins:
  # - serverless-apigw-binary
  - serverless-offline
  - serverless-prune-plugin
provider:
  name: aws
  runtime: nodejs14.x
  memorySize: 512
  timeout: 20
  httpApi:
    #cors:
      #allowCredentials: true
      #allowedOrigins:
        #- https://*
        #- http://*

    #cors: true
  # stage: ${opt:stage, 'dev'}
package:
  exclude: # By default exclude all files
    - ./**
  include: # Then start adding the relevant files/folder to package
    - 'dist/**'
    #- 'dist/ipe/server/**'
    #- 'dist/ipe/lambda/**'
    #- 'dist/ipe/**'
custom:
  #apigwBinary: # Library to add support for api gateway binary types
  #  types:
  #    - '*/*'
  serverless-offline:
    noPrependStageInUrl: true
functions:
  api:
    handler: dist/ipe/lambda/main.handler # A file lambda.js will hold fn handler
    events:
      - httpApi:
          method: '*'
          path: '*'
