name: Build Deploy
on:
  workflow_call:
    secrets:
      RTC_GITHUB_REGISTRY:
        required: true
      ENVIRONMENT_NAME:
        required: true
      SSH_DEPLOY_KEY:
        required: true
      TARGET_BRANCH:
        required: true
      DESTINATION_REPO:
        required: true
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - uses: actions/setup-node@v3
        name: Setup Node
        with:
          node-version: '16.x'
          registry-url: "https://npm.pkg.github.com"
      - run: npm install
        name: Install packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.RTC_GITHUB_REGISTRY }}
      - run: npm run prerender:${{ secrets.ENVIRONMENT_NAME }}
      - run: echo "::set-output name=stamp::$(date +'%Y%m%d%H%M%S')"
        name: Generate Release Stamp
        id: release
      - name: Push to build repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
        with:
          source-directory: 'dist/spear'
          destination-github-username: 'rollthecloudinc'
          destination-repository-name: ${{ secrets.DESTINATION_REPO }}
          target-branch: ${{ secrets.TARGET_BRANCH }}